// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5QzavW1a4DemZbyN7ys5r49gHGVWySE4',
    appId: '1:550245132857:web:6e831f96051991b9e3bbe8',
    messagingSenderId: '550245132857',
    projectId: 'twitch-clone-5784e',
    authDomain: 'twitch-clone-5784e.firebaseapp.com',
    storageBucket: 'twitch-clone-5784e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkYvS3v6EnulklvAHWyHKCnYVDobunN_0',
    appId: '1:550245132857:android:b745b26aa7e9f08be3bbe8',
    messagingSenderId: '550245132857',
    projectId: 'twitch-clone-5784e',
    storageBucket: 'twitch-clone-5784e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb3g5v2neAJAlXnwcrr9z1cKJc_p-AWuY',
    appId: '1:550245132857:ios:5cf0bd7c7fcf6454e3bbe8',
    messagingSenderId: '550245132857',
    projectId: 'twitch-clone-5784e',
    storageBucket: 'twitch-clone-5784e.appspot.com',
    iosClientId: '550245132857-hhmml1drdfrntsek46f4feapg0mlqcaq.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb3g5v2neAJAlXnwcrr9z1cKJc_p-AWuY',
    appId: '1:550245132857:ios:4f12bef5ebd3ba38e3bbe8',
    messagingSenderId: '550245132857',
    projectId: 'twitch-clone-5784e',
    storageBucket: 'twitch-clone-5784e.appspot.com',
    iosClientId: '550245132857-kq73be3811jd7l1ts45qvu1bpi00behp.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitch.RunnerTests',
  );
}
